import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Zubaan',
  description: 'Terms and conditions for using Zubaan.',
}

export default function TermsPage() {
  return (
    <div style={{ backgroundColor: '#14102A', minHeight: '100vh', color: '#F5F0EB' }}>
      <nav
        style={{
          borderBottom: '1px solid #2A1F4A',
          padding: '0 24px',
          height: 64,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <Link
          href="/"
          style={{ fontFamily: 'var(--font-fraunces)', fontStyle: 'italic', fontSize: 22, color: '#F4B942', textDecoration: 'none' }}
        >
          Zubaan
        </Link>
        <Link href="/" style={{ fontFamily: 'var(--font-inter)', fontSize: 13, color: '#8A84A8', textDecoration: 'none' }}>
          ← Back to home
        </Link>
      </nav>

      <main style={{ maxWidth: 740, margin: '0 auto', padding: '64px 24px 100px' }}>
        <p style={{ fontFamily: 'var(--font-inter)', fontWeight: 600, fontSize: 10, letterSpacing: 4, color: '#F4B942', textTransform: 'uppercase', marginBottom: 16 }}>
          Legal
        </p>
        <h1 style={{ fontFamily: 'var(--font-fraunces)', fontStyle: 'italic', fontSize: 'clamp(32px, 5vw, 52px)', color: '#F5F0EB', letterSpacing: '-1px', marginBottom: 8, lineHeight: 1.1 }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: 'var(--font-inter)', fontSize: 13, color: '#8A84A8', marginBottom: 48 }}>
          Last updated: April 19, 2026
        </p>
        <div style={{ height: 1, backgroundColor: '#2A1F4A', marginBottom: 48 }} />

        <S title="Acceptance of Terms">
          By downloading, installing, or using Zubaan, you agree to these Terms of Service.
          If you do not agree, please do not use the app. These terms apply to all users,
          including free and Pro subscribers.
        </S>

        <S title="What Zubaan Does">
          Zubaan is an AI-assisted reply generation app. You upload a screenshot of a chat
          conversation, and Zubaan provides suggested replies. The AI suggestions are tools
          to assist your communication — you are responsible for every message you ultimately
          send.
        </S>

        <S title="Acceptable Use">
          You agree not to use Zubaan to:
          <Bullets items={[
            'Generate content that is harassing, threatening, defamatory, or illegal.',
            'Upload screenshots containing private data of others without their consent.',
            'Circumvent usage limits or subscription enforcement through technical means.',
            'Scrape, reverse-engineer, or reproduce the AI output at scale.',
            'Use the service for any purpose that violates applicable law.',
          ]} />
          We reserve the right to suspend or terminate accounts that violate these rules.
        </S>

        <S title="AI-Generated Content">
          Replies generated by Zubaan are AI suggestions. We do not guarantee their accuracy,
          appropriateness, or suitability for any situation. You bear sole responsibility for
          reviewing and deciding whether to send any generated content.
        </S>

        <S title="Screenshots and Your Content">
          You retain ownership of any screenshots you upload. By uploading, you grant us a
          limited, temporary licence to process the image solely for reply generation. We do
          not claim ownership of your content. Screenshots are deleted after processing —
          see our Privacy Policy for details.
        </S>

        <S title="Subscriptions and Billing">
          Zubaan Pro is billed monthly through the App Store or Google Play. Subscriptions
          auto-renew unless cancelled at least 24 hours before the renewal date. All billing
          disputes are handled through the respective platform (Apple / Google). We do not
          offer refunds for partial periods.
        </S>

        <S title="Free Tier Limits">
          Free accounts are limited to 2 reply sets per day. Limits reset at midnight in
          your local timezone. We reserve the right to adjust free-tier limits with 7 days
          notice.
        </S>

        <S title="Availability">
          We aim for high availability but do not guarantee uninterrupted service. We may
          perform maintenance, update the AI model, or temporarily suspend the service
          without prior notice.
        </S>

        <S title="Intellectual Property">
          The Zubaan name, logo, and app design are our intellectual property. You may not
          reproduce or use them without written permission. The AI model and processing
          pipeline remain our proprietary technology.
        </S>

        <S title="Disclaimer of Warranties">
          Zubaan is provided &ldquo;as is&rdquo; without warranty of any kind. We disclaim all
          warranties, express or implied, including merchantability and fitness for a
          particular purpose.
        </S>

        <S title="Limitation of Liability">
          To the maximum extent permitted by law, Zubaan shall not be liable for any
          indirect, incidental, or consequential damages arising from your use of the app,
          including but not limited to relationship outcomes, reputational harm, or lost
          opportunities.
        </S>

        <S title="Changes to Terms">
          We may update these terms. Material changes will be communicated via in-app
          notification or email at least 7 days before taking effect. Continued use after
          changes constitutes acceptance.
        </S>

        <S title="Governing Law">
          These terms are governed by the laws of India. Any disputes shall be subject to
          the exclusive jurisdiction of the courts of India.
        </S>

        <S title="Contact">
          Questions about these terms?{' '}
          <a href="mailto:zubaan.live@gmail.com" style={{ color: '#F4B942', fontWeight: 600, textDecoration: 'none' }}>
            zubaan.live@gmail.com
          </a>
        </S>
      </main>

      <footer style={{ borderTop: '1px solid #2A1F4A', padding: '32px 24px', textAlign: 'center' }}>
        <p style={{ fontFamily: 'var(--font-inter)', fontSize: 12, color: '#8A84A8' }}>
          © 2026 Zubaan ·{' '}
          <Link href="/privacy" style={{ color: '#8A84A8', textDecoration: 'none' }}>Privacy</Link>
          {' · '}
          <Link href="/terms" style={{ color: '#8A84A8', textDecoration: 'none' }}>Terms</Link>
          {' · '}
          <Link href="/delete-account" style={{ color: '#8A84A8', textDecoration: 'none' }}>Delete account</Link>
          {' · '}
          <Link href="/contact" style={{ color: '#8A84A8', textDecoration: 'none' }}>Contact</Link>
        </p>
      </footer>
    </div>
  )
}

function S({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontFamily: 'var(--font-inter)', fontWeight: 600, fontSize: 16, color: '#F5F0EB', marginBottom: 12 }}>
        {title}
      </h2>
      <div style={{ fontFamily: 'var(--font-inter)', fontSize: 15, lineHeight: 1.75, color: '#8A84A8' }}>
        {children}
      </div>
    </div>
  )
}

function Bullets({ items }: { items: string[] }) {
  return (
    <ul style={{ marginTop: 12, paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
      {items.map((item, i) => (
        <li key={i} style={{ display: 'flex', gap: 10 }}>
          <span style={{ color: '#F4B942', flexShrink: 0, marginTop: 2 }}>·</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}
